name: Feature request
description: Suggest a new feature for VeloxERP
title: "[Feature Request]: "
labels: [ "new" ]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!

  - type: input
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: Is your feature request related to a problem? Please describe.
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/VeloxERP/VeloxERP/tree/main/.github/CODE_OF_CONDUCT).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true